---
- name: Install Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Add RKE SSH user to dockerroot group
  user:
    name: "{{ rke_ssh_user }}"
    groups: [docker]
    append: yes

- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ rke_kubernetes_version.split('-', 1)[0] }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    force: yes
    mode: "+rx"
# TODO figure out checksum BS


- name: Remove swap volumes from /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    # This should match all lines with an fstype of "swap"
    regexp: '^[^\s]+\s+[^\s]+\s+swap\s+'
  register: remove_swap_volumes

- name: Disable swap
  command: swapoff --all
  when: remove_swap_volumes is changed