# Install, configure and run Rancher Kubernetes Engine (RKE) on the target hosts to configure a Kubernetes cluster

- name: Download RKE binary
  get_url:
    url: "{{ rke_binary_url }}"
    checksum: "{{ rke_binary_checksum }}"
    dest: /usr/local/bin/rke
    mode: "+rx"
    force: yes
  become: yes
  register: rke_binary

- name: Ensure config directory exists
  file:
    path: "{{ rke_config_dir }}"
    state: directory

- name: Create/update RKE config file
  template:
    src: rke_cluster.yml
    dest: "{{ rke_config_dir }}/cluster.yml"
    mode: u=rw,g=r,o=
  register: rke_cluster_config

- name: Run RKE installer
  shell: |
    rke up > rke-up-$(date '+%Y-%m-%d_%H:%M:%S').log 2>&1
  args:
    chdir: "{{ rke_config_dir }}"
  when: rke_binary is changed or rke_cluster_config is changed or rke_force_configure
  #TODO: better check for what should be done with rke 

- name: Ensure $HOME/.kube exists
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy kubeconfig to default location
  copy:
    remote_src: yes
    src: "{{ rke_config_dir }}/kube_config_cluster.yml"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ rke_ssh_user }}"
    mode: "u=rw"

- name: Add stable Rancher chart repo
  shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable && helm repo update

- name: Deploy Rancher
  kubernetes.core.helm:
    release_name: rancher
    chart_ref: rancher-stable/rancher
    release_namespace: cattle-system
    create_namespace: true
    chart_version: "{{ rancher.version }}"
    values:
      hostname: "{{ rancher.hostname }}"
      bootstrapPassword: "{{ rancher.bootstrapPassword }}"
      ingress:
        tls:
          source: "{{ rancher.tls_source }}"
  when: rancher.enabled
