# Map of Kubernetes minor version to RKE Kubernetes version



kubernetes_supported_versions:
  "1.18": v1.18.20-rancher1-3
  "1.19": v1.19.16-rancher1-6
  "1.20": v1.20.15-rancher1-4

# Default Kubernetes minor version
kubernetes_version: "1.19"

rke_force_configure: false

cluster_name: rke01

rke_ssh_user: rke


rke_config_dir: home/{{ rke_ssh_user }}
log_path: "{{ rke_config_dir }}/ansible.log"

rke_release: v1.2.21
rke_binary_url: "https://github.com/rancher/rke/releases/download/{{ rke_release }}/rke_linux-amd64"
rke_binary_checksum: sha256:a873ab943143cd453e74b0fe0f6c5e6d8a9bba991695f4ffc2a21c4431d1a8ef
rke_kubernetes_version: "{{ kubernetes_supported_versions[kubernetes_version] }}"

# This is the host that will run 'rke up'
# By default, use the first host in the play
rke_controller_hostname: "{{ ansible_play_hosts[0] }}"

# Networking configuration
cluster_interface: "{{ ansible_default_ipv4.interface }}"
cluster_cidr: "{{ [ansible_facts[cluster_interface].ipv4.network, ansible_facts[cluster_interface].ipv4.netmask] | join('/') | ipaddr('net') }}"

rke_network_config:
  plugin: canal
  options:
    canal_iface: "{{ cluster_interface }}"

rke_ingress_config:
  provider: nginx