# Map of Kubernetes minor version to RKE Kubernetes version
kubernetes_supported_versions:
  "1.18": v1.18.20-rancher1-3
  "1.19": v1.19.16-rancher1-6
  "1.20": v1.20.15-rancher1-4
  "1.21": v1.21.13-rancher1-1
  "1.22": v1.22.10-rancher1-1
  "1.23": v1.23.7-rancher1-1

# Default Kubernetes minor version
kubernetes_version: "1.22"

rke_force_configure: false

cluster_name: rke01

rke_config_dir: .rke
rke_release: v1.3.12
rke_binary_url: "https://github.com/rancher/rke/releases/download/{{ rke_release }}/rke_linux-amd64"
rke_binary_checksum: sha256:579da2206aec09cadccd8d6f4818861e78a256b6ae550a229335e500a472bd50
rke_kubernetes_version: "{{ kubernetes_supported_versions[kubernetes_version] }}"

rke_ssh_user: rke

rke_ssh_private_key: "{{ lookup('file', 'keys/{{ cluster_name }}/id_rsa') }}"
rke_ssh_public_key: "{{ lookup('file', 'keys/{{ cluster_name }}/id_rsa.pub') }}"

# This is the host that will run 'rke up'
# By default, use the first host in the play
rke_controller_hostname: "{{ ansible_play_hosts[0] }}"

# Networking configuration
cluster_interface: "{{ ansible_default_ipv4.interface }}"
cluster_cidr: "{{ [ansible_facts[cluster_interface].ipv4.network, ansible_facts[cluster_interface].ipv4.netmask] | join('/') | ipaddr('net') }}"

rke_network_config:
  plugin: canal
  options:
    canal_iface: "{{ cluster_interface }}"

rke_ingress_config:
  provider: nginx