NUM_WORKER_NODES=2
IP_NW="172.31.0."
IP_START=10
PROVIDER="qemu"

Vagrant.configure(2) do |config|

  config.vm.provider PROVIDER do |prov|
    prov.arch = "x86_64"
    prov.machine = "q35"
    prov.cpu = "max"
    prov.net_device = "virtio-net-pci"
  end

  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2204"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: IP_NW + "#{IP_START}"
    master.vm.provider PROVIDER do |prov|
      prov.ssh_port = 5022
    end
  end

  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "worker0#{i}" do |node|
      node.vm.box = "generic/ubuntu2204"
      node.vm.hostname = "worker0#{i}"
      node.vm.network "private_network", ip: IP_NW + "#{IP_START + i}"
      node.vm.provider PROVIDER do |prov|
        prov.ssh_port = 5022+i
      end
    end
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
    #TODO make this automatic
    ansible.host_vars = {
      "master" => {"rke_node_roles" => "master, worker"},
      "worker01" => {"rke_node_roles" => "worker"},
      "worker02" => {"rke_node_roles" => "worker"}
    }
  end

end
